app/cvs/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import InputRequired

class AddCvForm(FlaskForm):
    name = StringField('CV Name:', validators=[InputRequired()])

app/interests/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import InputRequired

class AddInterestForm(FlaskForm):
    name = StringField('Interest Name:', validators=[InputRequired()])

app/letters/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SelectField, DateField, TextAreaField
from wtforms.validators import InputRequired

class AddContentForm(FlaskForm):
    name = StringField('Name:', validators=[InputRequired()])
    description = TextAreaField('Letter content:', validators=[InputRequired()], render_kw={'rows': 20})

class EditContentForm(FlaskForm):
    id = IntegerField('Experience ID:', validators=[InputRequired()], render_kw={'readonly': True})
    name = StringField('Name:', validators=[InputRequired()])
    description = TextAreaField('Letter content:', validators=[InputRequired()], render_kw={'rows': 20})

app/projects/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, IntegerField
from wtforms.validators import InputRequired

class AddProjectForm(FlaskForm):
    name = StringField('Project Name:', validators=[InputRequired()])
    description = TextAreaField('Description:', validators=[InputRequired()], render_kw={'rows': 5})

class EditProjectForm(FlaskForm):
    id = IntegerField('Project ID:', validators=[InputRequired()], render_kw={'readonly': True})
    name = StringField('Project Name:', validators=[InputRequired()])
    description = TextAreaField('Description:', validators=[InputRequired()], render_kw={'rows': 5})

app/cvs/routes.py
from flask import render_template, redirect, request, url_for, flash, Blueprint
from flask_sqlalchemy import SQLAlchemy

from app.models import Cv, Details, Content, Letter, Summary, Experience, Education, Interest, Skill, Project
from app.cvs.forms import AddCvForm

from app import db

from PyPDF2 import PdfFileReader
import pdfkit
import shutil
import os.path

from os import path

# Initialising the cvs blueprint.
cvs = Blueprint('cvs', __name__)


# The route for displaying, editing and creating summaries.

@cvs.route("/", methods=['GET', 'POST'])
@cvs.route("/cvs", methods=['GET', 'POST'])
def cv():

    form=AddCvForm()

    cv=Cv.query.all()

    detail = Details.query.filter(Details.id == 1).first()
    summary = Summary.query.filter(Summary.active == 1).first()
    experience = Experience.query.filter(Experience.active == 1).all()
    education = Education.query.filter(Education.active == 1).all()
    project = Project.query.filter(Project.active == 1).all()
    skill = Skill.query.filter(Skill.active == 1).all()
    interest = Interest.query.filter(Interest.active == 1).all()

    for c in cv:
        filename=c.name.replace(" ", "_")

        if path.exists("app/static/cvs/" + filename + ".pdf"):
            c.generated = 1

            db.session.commit()
        else:
            c.generated = 0

            db.session.commit()

        if path.exists("app/static/letters/" + filename + "_letter.pdf"):
            c.letter.generated = 1

            db.session.commit()
        else:
            c.letter.generated = 0

            db.session.commit()

    if request.method=='POST':

        if request.form['submit_button'] == 'Add CV' and form.validate_on_submit():

            content = Content.query.filter(Content.active == 1).first()

            letter = Letter(content=content)

            db.session.add(letter)
            db.session.commit()

            cv = Cv(name=form.name.data,
                    details_id=detail.id,
                    letter=letter)
            
            db.session.add(cv)
            db.session.commit()

            cv.summary = summary

            for e in experience:
                if e.active == 1:
                    cv.experience.append(e)

            for e in education:
                if e.active == 1:
                    cv.education.append(e)

            for p in project:
                if p.active == 1:
                    cv.projects.append(p)

            for s in skill:
                if s.active == 1:
                    cv.skills.append(s)

            for i in interest:
                if i.active == 1:
                    cv.interests.append(i)
        

            db.session.commit()

            flash('Successfully added CV', 'success')
            return redirect(url_for('cvs.cv'))

    return render_template('cv.html', title = 'CVs', form=form, cv=cv, detail=detail, experience=experience, education=education,
        skill=skill, interest=interest, project=project, summary=summary)



# The route for generating a PDF of a CV.

@cvs.route("/generate-cv/<id>")
def generateCv(id):

    c = Cv.query.filter(Cv.id == id).first()

    exp = c.experience
    exp.sort(key=lambda x: x.end_date, reverse=True)

    edu = c.education
    edu.sort(key=lambda x: x.end_date, reverse=True)

    proj= c.projects
    proj.sort(key=lambda x: x.id)

    css=['app/static/css/bootstrap.min.css', 'app/static/css/circle.css']

    
    filename= c.name + '.pdf'

    filename=filename.replace(" ", "_")

    linkedin_url= os.getcwd() + "/app/static/images/linkedin.png"
    email_url= os.getcwd() + "/app/static/images/email.png"
    phone_url= os.getcwd() + "/app/static/images/phone.png"
    gitlab_url= os.getcwd() + "/app/static/images/gitlab.svg"
    bullet_url = os.getcwd() + "/app/static/images/circle.png"
    location_url = os.getcwd() + "/app/static/images/location.png"

    
    cv = render_template('cv-layout1.html', linkedin_url=linkedin_url, email_url=email_url, phone_url=phone_url, location_url=location_url,
        gitlab_url=gitlab_url, bullet_url=bullet_url, c=c, proj=proj, exp=exp, edu=edu, nonprogress_colour="white", progress_colour="#304145",
        writing_colour2="black", writing_colour="white", header_background_colour="#304145", side_background_colour="#a5b7c0")

    options = {
    'user-style-sheet':css,
    'encoding': 'UTF-8',        
    'margin-left': '0mm',
    'margin-right': '0mm',
    'margin-bottom': '0mm',
    'margin-top': '0mm'
    }

    pdfkit.from_string(cv, filename, options=options, css=css)
    filess = [filename]
    for f in filess:
        shutil.move(f, 'app/static/cvs')

    flash('Successfully generated CV', 'success')
    return redirect(url_for('cvs.cv'))



# The route for generating a PDF of a Letter.

@cvs.route("/generate-letter/<id>")
def generateLetter(id):

    c = Cv.query.filter(Cv.id == id).first()

    l = c.letter

    css=['app/static/css/bootstrap.min.css']
    
    filename= c.name + '_letter.pdf'

    filename=filename.replace(" ", "_")

    linkedin_url= os.getcwd() + "/app/static/images/linkedin.png"
    email_url= os.getcwd() + "/app/static/images/email.png"
    phone_url= os.getcwd() + "/app/static/images/phone.png"
    gitlab_url= os.getcwd() + "/app/static/images/gitlab.svg"
    bullet_url = os.getcwd() + "/app/static/images/circle.png"
    location_url = os.getcwd() + "/app/static/images/location.png"

    
    letter = render_template('letter-layout1.html', linkedin_url=linkedin_url, email_url=email_url, phone_url=phone_url, location_url=location_url,
        gitlab_url=gitlab_url, c=c,
        writing_colour2="black", writing_colour="white", header_background_colour="#111e2f", side_background_colour="#98979b")

    options = {
    'user-style-sheet':css,
    'encoding': 'UTF-8',        
    'margin-left': '0mm',
    'margin-right': '0mm',
    'margin-bottom': '0mm',
    'margin-top': '0mm'
    }

    pdfkit.from_string(letter, filename, options=options, css=css)
    filess = [filename]
    for f in filess:
        shutil.move(f, 'app/static/letters')

    flash('Successfully generated Letter', 'success')
    return redirect(url_for('cvs.cv'))


# The route for displaying the PDF created for a CV.

@cvs.route("/view-cv/<id>", methods=['GET'])
def viewCv(id):

    c = Cv.query.filter(Cv.id == id).first()

    filename=c.name.replace(" ", "_")

    cv_url = '/static/cvs/' + filename + '.pdf'

    return render_template('cvpdf.html', title=c.name, cv_url=cv_url)


# The route for displaying the PDF created for a Letter.

@cvs.route("/view-letter/<id>", methods=['GET'])
def viewLetter(id):

    c = Cv.query.filter(Cv.id == id).first()

    filename=c.name.replace(" ", "_")

    letter_url = '/static/letters/' + filename + '_letter.pdf'

    return render_template('letterpdf.html', title=c.name, letter_url=letter_url)


# The route for deleting a CV.

@cvs.route("/delete-cv/<id>")
def deleteCv(id):

    c = Cv.query.filter(Cv.id == id).first()

    if c.generated:
        filename=c.name.replace(" ", "_")
        os.remove("app/static/cvs/" + filename + ".pdf")

    if c.letter.generated:
        filename=c.name.replace(" ", "_")
        os.remove("app/static/letters/" + filename + "_letter.pdf")

    db.session.delete(c.letter)
    db.session.delete(c)
    db.session.commit()

    flash('Successfully deleted CV', 'success')
    return redirect(url_for('cvs.cv'))

app/educations/routes.py
from flask import render_template, redirect, request, url_for, flash, Blueprint
from flask_sqlalchemy import SQLAlchemy

from app import db

from app.models import Education
from app.educations.forms import AddEducationForm, EditEducationForm


# Initialising the education blueprint.
educations = Blueprint('educations', __name__)


# The route for displaying, editing and creating education.

@educations.route("/education", methods=['GET', 'POST'])
def education():

    form=AddEducationForm()
    eform=EditEducationForm()

    education = Education.query.all()

    education.sort(key=lambda x: x.end_date, reverse=True)

    if request.method == 'POST':

        if request.form['submit_button'] == "Add Education" and form.validate_on_submit():

            if form.grade.data:
                education = Education(school=form.school.data,
                                    course=form.course.data,
                                    grade=form.grade.data,
                                    start_date=form.start_date.data,
                                    end_date=form.end_date.data,
                                    description=form.description.data)
            else:
                education = Education(school=form.school.data,
                                    course=form.course.data,
                                    expected_grade=form.expected_grade.data,
                                    start_date=form.start_date.data,
                                    end_date=form.end_date.data,
                                    description=form.description.data)

            db.session.add(education)
            db.session.commit()

            flash('Successfully added education', 'success')
            return redirect(url_for('educations.education'))

        elif request.form['submit_button'] == "Save Changes" and form.validate_on_submit():

            education = Education.query.filter(Education.id == eform.id.data).first()

            if eform.confirmed.data == "Confirmed":
                education.school = eform.school.data
                education.course = eform.course.data
                education.grade = eform.grade.data
                education.expected_grade = None
                education.start_date = eform.start_date.data
                education.end_date = eform.end_date.data
                education.description = eform.description.data
            
            else:
                education.school = eform.school.data
                education.course = eform.course.data
                education.grade = None
                education.expected_grade = eform.grade.data
                education.start_date = eform.start_date.data
                education.end_date = eform.end_date.data
                education.description = eform.description.data

            db.session.commit()

            flash('Successfully updated education', 'success')
            return redirect(url_for('educations.education'))


    return render_template('education.html', title='Education', form=form, eform=eform, education=education)


# The route for deleting education.

@educations.route("/delete-education/<id>")
def deleteEducation(id):

    education = Education.query.filter(Education.id == id).first()

    db.session.delete(education)
    db.session.commit()

    flash('Successfully deleted education', 'success')
    return redirect(url_for('educations.education'))


# The route for actviating education.

@educations.route("/activate-education/<id>")
def activateEducation(id):

    education = Education.query.filter(Education.id == id).first()

    education.active = 1
    db.session.commit()

    flash('Successfully activated education', 'success')
    return redirect(url_for('educations.education'))


# The route for inactivating education.

@educations.route("/inactivate-education/<id>")
def inactivateEducation(id):

    education = Education.query.filter(Education.id == id).first()

    education.active = 0
    db.session.commit()

    flash('Successfully inactivated education', 'success')
    return redirect(url_for('educations.education'))

app/interests/routes.py
from flask import render_template, redirect, request, url_for, flash, Blueprint
from flask_sqlalchemy import SQLAlchemy

from app import db

from app.models import Interest
from app.interests.forms import AddInterestForm


#Initialising the interests blueprint.
interests = Blueprint('interests', __name__)


# The route for displaying and creating interests.

@interests.route("/interests-and-hobbies", methods=['GET', 'POST'])
def interest():

    form=AddInterestForm()

    interest = Interest.query.all()

    if request.method == 'POST':

        if request.form['submit_button'] == "Add Interest" and form.validate_on_submit():

            interest = Interest(name=form.name.data)

            db.session.add(interest)
            db.session.commit()

            flash('Successfully added interest', 'success')
            return redirect(url_for('interests.interest'))

    return render_template('interests.html', title = 'Interests & Hobbies', form=form, interest=interest)


# The route for deleting interets.

@interests.route("/delete-interest/<id>")
def deleteInterest(id):

    interest = Interest.query.filter(Interest.id == id).first()

    db.session.delete(interest)
    db.session.commit()

    flash('Successfully deleted interest', 'success')
    return redirect(url_for('interests.interest'))


# The route for activating interests.

@interests.route("/activate-interest/<id>")
def activateInterest(id):

    interest = Interest.query.filter(Interest.id == id).first()

    interest.active = 1
    db.session.commit()

    flash('Successfully activated interest', 'success')
    return redirect(url_for('interests.interest'))


# The route for inactivating interests.

@interests.route("/inactivate-interest/<id>")
def inactivateInterest(id):

    interest = Interest.query.filter(Interest.id == id).first()

    interest.active = 0
    db.session.commit()

    flash('Successfully inactivated interest', 'success')
    return redirect(url_for('interests.interest'))

app/letters/routes.py
from flask import render_template, redirect, request, url_for, flash, Blueprint
from flask_sqlalchemy import SQLAlchemy

from app import db

from app.models import Content
from app.letters.forms import AddContentForm, EditContentForm


# Initialising the letters blueprint.
letters = Blueprint('letters', __name__)


# The route for displaying, editing and creating letter content.

@letters.route("/letter-content", methods=['GET', 'POST'])
def content():

    form=AddContentForm()
    eform=EditContentForm()

    content = Content.query.all()

    if request.method == 'POST':

        if request.form['submit_button'] == "Add Content" and form.validate_on_submit():


            content = Content(name=form.name.data,
                            description=form.description.data)

            db.session.add(content)
            db.session.commit()

            flash('Successfully added content', 'success')
            return redirect(url_for('letters.content'))

        elif request.form['submit_button'] == "Save Changes" and form.validate_on_submit():

            content = Content.query.filter(Content.id == eform.id.data).first()

            content.name = eform.name.data
            content.description = eform.description.data

            db.session.commit()

            flash('Successfully updated content', 'success')
            return redirect(url_for('letters.content'))


    return render_template('letters.html', title='Letter Content', form=form, eform=eform, content=content)


# The route for deleting letter content.

@letters.route("/delete-content/<id>")
def deleteContent(id):

    content = Content.query.filter(Content.id == id).first()

    db.session.delete(content)
    db.session.commit()

    flash('Successfully deleted content', 'success')
    return redirect(url_for('letters.content'))


# The route for activating letter content.

@letters.route("/activate-content/<id>")
def activateContent(id):

    content = Content.query.filter(Content.id == id).first()

    content.active = 1
    db.session.commit()

    flash('Successfully activated content', 'success')
    return redirect(url_for('letters.content'))


# The route for inactivating letter content.

@letters.route("/inactivate-content/<id>")
def inactivateContent(id):

    content = Content.query.filter(Content.id == id).first()

    content.active = 0
    db.session.commit()

    flash('Successfully inactivated content', 'success')
    return redirect(url_for('letters.content'))

app/templates/cv.html
{% extends "navbar.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-lg">
            <h2>CVs</h2>
            <h5 style="color:red;">Check The Contents Of The CV Are Correct Before Confirming The Create CV Form </h5>
        </div>
    </div>

    <div class="row">
        <div class="col-lg">
            <table id="table" class="table table-hover">

                <!-- Table Header -->
                <thead class="thead-light">
                    <tr>
                        <th>
                            Name
                        </th>
                        <th>
                            Generate CV PDF
                        </th>
                        <th>
                            View CV PDF
                        </th>
                        <th>
                            Generate Letter PDF
                        </th>
                        <th>
                            View Letter PDF
                        </th>
                        <th>
                            Delete
                        </th>
                    </tr>
                </thead>
                <tbody>

                    {% for c in cv %}
                    <tr>
                        <td>
                            {{c.name}}
                        </td>
                        {% if c.generated %}
                        <td></td>
                        <td>
                            <a class="btn btn-dark" href="{{url_for('cvs.viewCv', id=c.id)}}"
                                role="button">View</a>
                        </td>
                        {% else %}
                        <td>
                            <a class="btn btn-success" href="{{url_for('cvs.generateCv', id=c.id)}}"
                                role="button">Generate</a>
                        </td>
                        <td></td>
                        {% endif %}
                        {% if c.letter.generated %}
                        <td></td>
                        <td>
                            <a class="btn btn-dark" href="{{url_for('cvs.viewLetter', id=c.id)}}"
                                role="button">View</a>
                        </td>
                        {% else %}
                        <td>
                            <a class="btn btn-success" href="{{url_for('cvs.generateLetter', id=c.id)}}"
                                role="button">Generate</a>
                        </td>
                        <td></td>
                        {% endif %}
                        <td>
                            <a class="btn btn-danger" href="{{url_for('cvs.deleteCv', id=c.id)}}"
                                role="button">Delete</a>
                        </td>
                    </tr>
                    {% endfor %}

                </tbody>
            </table>
        </div>
    </div>

    <div class="row">
        <div class="col-sm">
            <btn class="btn-primary btn" data-toggle="modal" data-target="#addCvModal">
                Create CV
            </btn>
        </div>
    </div>

    <div class="modal fade" id="addCvModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Create CV</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>

                <!-- Form Contents -->
                <div class="modal-body">
                    <form method="post">
                        {{ form.csrf_token }}
                        <div class="form-group">
                            {{ wtf.form_field(form.name) }}
                        </div>
                        <div>
                            <p >Summary:<br>
                                {{summary.description}}
                            </p>
                        </div>
                        <div>
                            <p >Projects:<br>
                                {% for p in project %}
                                {{p.name}}<br>
                                {% endfor %}
                            </p>
                            
                        </div>
                        <div>
                            <p >Work Experience:<br>
                                {% for e in experience %}
                                {{e.workplace}} - {{e.title}}<br>
                                {% endfor %}
                            </p>
                            
                        </div>
                        <div>
                            <p >Education:<br>
                                {% for e in education %}
                                {{e.school}} - {{e.course}}<br>
                                {% endfor %}
                            </p>
                            
                        </div>
                        <div>
                            <p >Skills:<br>
                                {% for s in skill %}
                                {{s.name}} - {{s.sort}}<br>
                                {% endfor %}
                            </p>
                            
                        </div>
                        <div>
                            <p >Interests & Hobbies:<br>
                                {% for i in interest %}
                                {{i.name}}<br>
                                {% endfor %}
                            </p>
                            
                        </div>
                        <div class="form-group">
                            <input class="btn btn-primary" type="submit" name="submit_button"
                                value="Add CV"></input>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

app/templates/cvpdf.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>CV - {{title}} | CV Generator</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
    <div class="containter">
        <embed src="{{ cv_url }}" type="application/pdf" width="100%" height="1000px"/>
    </div>
</body>

</html>

app/templates/interests.html
{% extends "navbar.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-lg">
            <h2>Interests & Hobbies</h2>
            <h5 style="color:red;">Activate 2-5 Interests</h5>
        </div>
    </div>

    <div class="row">
        <div class="col-lg">
            <table id="table" class="table table-hover">

                <!-- Table Header -->
                <thead class="thead-light">
                    <tr>
                        <th>
                            Interest
                        </th>
                        <th>
                            Active
                        </th>
                        <th>
                            Delete
                        </th>
                    </tr>
                </thead>
                <tbody>

                    {% for i in interest %}
                    <tr>
                        <td>
                            {{i.name}}
                        </td>
                        {% if i.active %}
                        <td>
                            <a class="btn btn-warning" href="{{url_for('interests.inactivateInterest', id=i.id)}}"
                                role="button">Inactivate</a>
                        </td>
                        {% else %}
                        <td>
                            <a class="btn btn-success" href="{{url_for('interests.activateInterest', id=i.id)}}"
                                role="button">Activate</a>
                        </td>
                        {% endif %}
                        <td>
                            <a class="btn btn-danger" href="{{url_for('interests.deleteInterest', id=i.id)}}"
                                role="button">Delete</a>
                        </td>
                    </tr>
                    {% endfor %}

                </tbody>
            </table>
        </div>
    </div>

    <div class="row">
        <div class="col-sm">
            <btn class="btn-primary btn" data-toggle="modal" data-target="#addInterestModal">
                Add Interest
            </btn>
        </div>
    </div>

    <div class="modal fade" id="addInterestModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Add Interest</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>

                <!-- Form Contents -->
                <div class="modal-body">
                    <form method="post">
                        {{ form.csrf_token }}
                        <div class="form-group">
                            {{ wtf.form_field(form.name) }}
                        </div>
                        <div class="form-group">
                            <input class="btn btn-primary" type="submit" name="submit_button"
                                value="Add Interest"></input>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

app/templates/letterpdf.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Letter - {{title}} | CV Generator</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
    <div class="containter">
        <embed src="{{ letter_url }}" type="application/pdf" width="100%" height="1000px"/>
    </div>
</body>

</html>

app/templates/navbar.html
{% extends "bootstrap/base.html" %}

{% block styles %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<link rel="shortcut icon" type="image/png" href="{{ url_for('static', filename='images/logo.png') }}">

<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/circle.css')}}">
{% endblock %}


{% block scripts %}

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
    crossorigin="anonymous"></script>

<script  type="text/javascript" src="{{url_for('static', filename='js/circle.js')}}"></script>

{% endblock %}



{% block title %} {{title}} | CV Generator {% endblock %}


{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-light" style="background-color:#FFFFFF; ">

    <a class="navbar-brand" href="{{ url_for('cvs.cv') }}">
        <img class="img-fluid" id="brand-image" src="{{ url_for('static', filename='images/logo.png')}}"
            class="img-responsive" alt="">
    </a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation"><span
            class="navbar-toggler-icon"></span></button>

    <div class="collapse navbar-collapse" id="navbarNavDropdown">

        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('cvs.cv') }}">CVs<span
                        class="sr-only">(current)</span></a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('details.personalDetails') }}">Personal Details</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('letters.content') }}"> Letter Content</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('summaries.summary') }}"> Personal Summaries</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('projects.project') }}">Projects</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('educations.education') }}">Education</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('experiences.workExperience') }}">Work Experience</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('skills.skill') }}">Skills</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('interests.interest') }}">Interests & Hobbies</a>
            </li>
        </ul>
    </div>
</nav>
{% endblock %}

{% block content %}

{% endblock %}